### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by chikuwa-pan** [chikuwa-pan/furima-39525#23]
## フリマアプリのURL
https://furima-39525.onrender.com/

## Basic認証のIDとパスワード
ID:furima
password:1111

## 出品者用のメールアドレスとパスワード
mail:user1@test
password:test01

## 購入者用のメールアドレスとパスワード
mail:user2@test
password:test02

お手数ですがご確認よろしくお願いいたします！

**Comment by chikuwa-pan** [comment]
ご確認いただきありがとうございました！

ご指摘いただいた箇所を修正いたしましたので、お手数ですが再度いただけますでしょうか。
よろしくお願いいたします。

**Comment by mo1015** [comment]
@chikuwa-pan さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼箇所の修正が確認できました🎉
もう一点修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
「都道府県」を入力しなくても商品が購入できてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chikuwa-pan** [comment]
度々申し訳ございません。
改めてご確認お願いいたします・

**Comment by motomuun** [comment]
@chikuwa-pan さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回依頼した箇所は修正出来ておりましたが、別で修正が必要な箇所が発生しております。
今一度、以下のご確認をお願いします！

[修正依頼箇所]

**商品購入機能の確認**

- [ ] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
クレジットカードの情報を入力するフォームに値が入力出来ませんでした。入力できるように修正をお願いします。

- [ ] **エラーハンドリングができていること（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）**
購入ページに情報を入力し「購入」ボタンを押した後、再度情報を編集してボタンを押してもエラーハンドリングの情報が変わりません。「購入」ボタンを押すと、そのときに入力している情報に合わせてエラーメッセージが更新されるように修正をお願いします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by chikuwa-pan** [comment]
何度も申し訳ございません。
修正いたしましたので再度よろしくお願いいたします。
